export MAIL=aparvin@student.42berlin.de

autoload -U colors && colors
PROMPT='%F{green}%~ %F{reset_color}'

mkcd ()
{
	mkdir -p -- "$1" && cd -P -- "$1"
}

alias view="xdg-open"
alias open="evince"
alias vv="vim ~/.vimrc"
alias cw="gcc -Wall -Wextra -Werror"
alias nn="norminette -R CheckForbiddenSourceHeader"
alias ga="git add"
alias gaa="git add ."
alias gc="git commit -m"
alias gcl="git clone"
alias gp="git push"
alias gpl="git pull"
alias gl="git log"
alias gs="git status"
alias sz="source ~/.zshrc"
alias vz="vim ~/.zshrc"
alias v="vim"
alias c="clear"
alias lsd="ls -a -l"
alias work="cd ~/Core/libft/"
alias mk="mkdir"
alias t="touch"
alias war="bash ~/Core/libft/war/grademe.sh ~/Core/libft/src . -b -u"
alias war_1="bash ~/Core/libft/war/grademe.sh ~/Core/libft/src . -op1 -u"
alias war_2="bash ~/Core/libft/war/grademe.sh ~/Core/libft/src . -op2 -u"
alias tst="bash ~/Core/libft/war/grademe.sh $1 -u"
alias deep="cat /nfs/homes/aparvin/Core/libft/war/deepthought"

alias francinette=/nfs/homes/aparvin/francinette/tester.sh

alias paco=/nfs/homes/aparvin/francinette/tester.sh
