# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: aparvin <aparvin@student.42berlin.de>      +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/12/05 12:36:53 by aparvin           #+#    #+#              #
#    Updated: 2022/12/13 19:02:42 by aparvin          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

	NAME		= libft.a

	#COMPILER
	CC			= gcc
	CFLAGS		= -Wall -Wextra -Werror
	
	#DIRECTORIES
	SRCDIR		= src/
	INCLUDES	= inc/

	#SOURCE
	SRC			= $(wildcard $(SRCDIR)/*.c)

	#OBJECTS
	OBJ			= $(SRC:$(SRCDIR)/%.c=$(OBJDIR)%.o)

